# Cross-validates ComplexSpectrogram, FormantPath, TextGrid (silences), and
# KlattGrid synthesis -- both pladdrr's scalar and SIMD code paths -- against
# real Praat.app golden references. See test-simd-vs-praat-golden.R for the
# rationale. Goldens are committed CSVs generated by
# data-raw/generate_simd_goldens.R; this suite never shells out to Praat.

fixture_dir <- test_path("fixtures/simd-golden")

mono_fixtures <- c("tone_200hz", "tone_120hz_low", "silence", "complex_tone")

golden_path <- function(fixture, suffix) {
  file.path(fixture_dir, paste0(fixture, "_", suffix, "_golden.csv"))
}

with_simd <- function(enabled, code) {
  old <- pladdrr_simd()$enabled
  on.exit(pladdrr_simd(old))
  pladdrr_simd(enabled)
  force(code)
}

for (fixture in mono_fixtures) {
  wav_path <- file.path(fixture_dir, paste0(fixture, ".wav"))

  for (simd_enabled in c(FALSE, TRUE)) {
    label <- if (simd_enabled) "SIMD" else "scalar"

    test_that(paste0("ComplexSpectrogram matches Praat.app golden (", fixture, ", ", label, ")"), {
      # Praat.app 6.4.47 itself asserts/crashes on "ComplexSpectrogram: To
      # Sound" for these fixtures, so amplitude/phase resynthesis cannot be
      # golden-tested directly; validated indirectly via the power spectrum
      # derived from it (Down to Spectrogram), which exercises the same
      # underlying STFT computation as complexspectrogram_simd.
      skip_if_not(file.exists(wav_path), "golden fixture missing; run data-raw/generate_simd_goldens.R")
      with_simd(simd_enabled, {
        snd <- Sound(wav_path)
        cs <- snd$to_complex_spectrogram()
        spec <- cs$to_spectrogram()
        golden <- read.csv(golden_path(fixture, "complexspectrogram"))

        power <- vapply(seq_len(nrow(golden)), function(i) {
          spec$get_power_at(golden$time[i], golden$freq[i])
        }, numeric(1))
        expect_equal(10 * log10(pmax(power, 1e-30)),
                     10 * log10(pmax(golden$power, 1e-30)),
                     tolerance = 1e-2)
      })
    })

    test_that(paste0("FormantPath matches Praat.app golden (", fixture, ", ", label, ")"), {
      skip_if_not(file.exists(wav_path), "golden fixture missing; run data-raw/generate_simd_goldens.R")
      with_simd(simd_enabled, {
        snd <- Sound(wav_path)
        fp <- snd$to_formant_path()
        golden <- read.csv(golden_path(fixture, "formantpath"), colClasses = "character")
        golden_oc <- suppressWarnings(as.numeric(golden$optimal_ceiling[1]))
        golden_st <- suppressWarnings(as.numeric(golden$stress_candidate5[1]))

        oc <- fp$get_optimal_ceiling(parameters = c(1, 1, 1, 1, 1), powerf = 1.25)
        st <- fp$get_stress_of_candidate(from_formant = 1L, to_formant = 5L,
                                          parameters = c(1, 1, 1, 1, 1), powerf = 1.25, candidate = 5L)
        if (is.na(golden_st)) {
          expect_true(is.nan(st) || is.na(st))
        } else {
          expect_equal(st, golden_st, tolerance = 1e-3)
        }
        if (is.na(golden_oc)) {
          expect_true(is.nan(oc) || is.na(oc))
        } else {
          expect_equal(oc, golden_oc, tolerance = 1e-3)
        }
      })
    })

    test_that(paste0("TextGrid (silences) matches Praat.app golden (", fixture, ", ", label, ")"), {
      skip_if_not(file.exists(wav_path), "golden fixture missing; run data-raw/generate_simd_goldens.R")
      with_simd(simd_enabled, {
        snd <- Sound(wav_path)
        intensity <- snd$to_intensity()
        tg <- intensity$to_textgrid_silences(silence_threshold = -25.0,
                                              min_silence_duration = 0.1,
                                              min_sounding_duration = 0.05)
        golden <- read.csv(golden_path(fixture, "textgrid_silences"))

        expect_equal(tg$get_number_of_intervals(1), golden$n_intervals[1], tolerance = sqrt(.Machine$double.eps))
        expect_equal(tg$get_label_at_time(1, 0.0 + 1e-9), golden$label1[1], tolerance = sqrt(.Machine$double.eps))
      })
    })
  }
}

# --- KlattGrid synthesis (standalone, not tied to a Sound fixture) -----
for (simd_enabled in c(FALSE, TRUE)) {
  label <- if (simd_enabled) "SIMD" else "scalar"

  test_that(paste0("KlattGrid vowel synthesis matches Praat.app golden (", label, ")"), {
    golden_csv <- file.path(fixture_dir, "klattgrid_vowel_golden.csv")
    skip_if_not(file.exists(golden_csv), "golden fixture missing; run data-raw/generate_simd_goldens.R")
    with_simd(simd_enabled, {
      kg <- klattgrid_create_from_vowel(
        duration = 0.3, f0start = 125,
        f1 = 800, b1 = 80, f2 = 1200, b2 = 80, f3 = 2300, b3 = 100, f4 = 2800,
        bandWidthFraction = 0.05, formantFrequencyInterval = 1000
      )
      snd <- kg$to_sound()
      vals <- snd$get_values(channel = 1)
      golden <- read.csv(golden_csv)
      expect_equal(vals[golden$sample], golden$value, tolerance = 1e-5)
    })
  })
}
