# Cross-validates Formant, Harmonicity, MFCC, Spectrogram, PowerCepstrogram
# (CPPS), Pre-emphasis, Resample, Scale peak, and stereo-to-mono conversion
# -- both pladdrr's scalar and SIMD code paths -- against real Praat.app
# golden references. See test-simd-vs-praat-golden.R for Pitch/Intensity and
# the rationale (internal SIMD-vs-scalar parity can't catch a bug shared by
# both paths; only real ground truth can).
#
# Goldens are committed CSVs generated by data-raw/generate_simd_goldens.R;
# this suite never shells out to Praat.

fixture_dir <- test_path("fixtures/simd-golden")

mono_fixtures <- c("tone_200hz", "tone_120hz_low", "silence", "complex_tone")

golden_path <- function(fixture, suffix) {
  file.path(fixture_dir, paste0(fixture, "_", suffix, "_golden.csv"))
}

# Praat prints unvoiced/undefined frames as the literal string "--undefined--"
# (see Pitch); read as character and coerce so those become NA instead of
# breaking numeric columns.
read_golden_numeric <- function(path) {
  df <- read.csv(path, colClasses = "character")
  for (col in names(df)) {
    if (col != "frame" && col != "sample") {
      df[[col]] <- suppressWarnings(as.numeric(df[[col]]))
    }
  }
  df
}

with_simd <- function(enabled, code) {
  old <- pladdrr_simd()$enabled
  on.exit(pladdrr_simd(old))
  pladdrr_simd(enabled)
  force(code)
}

for (fixture in mono_fixtures) {
  wav_path <- file.path(fixture_dir, paste0(fixture, ".wav"))

  for (simd_enabled in c(FALSE, TRUE)) {
    label <- if (simd_enabled) "SIMD" else "scalar"

    test_that(paste0("Formant matches Praat.app golden (", fixture, ", ", label, ")"), {
      skip_if_not(file.exists(wav_path), "golden fixture missing; run data-raw/generate_simd_goldens.R")
      with_simd(simd_enabled, {
        snd <- Sound(wav_path)
        formant <- snd$to_formant()
        golden <- read_golden_numeric(golden_path(fixture, "formant"))

        expect_equal(formant$get_number_of_frames(), nrow(golden))

        for (col in c("f1", "f2", "f3")) {
          fnum <- match(col, c("f1", "f2", "f3"))
          vals <- vapply(seq_len(nrow(golden)), function(i) {
            formant$get_value_at_time(fnum, golden$time[i], unit = "hertz", interpolation = "linear")
          }, numeric(1))
          defined <- !is.na(golden[[col]])
          expect_equal(vals[defined], golden[[col]][defined], tolerance = 1e-3)
        }
      })
    })

    test_that(paste0("Harmonicity matches Praat.app golden (", fixture, ", ", label, ")"), {
      skip_if_not(file.exists(wav_path), "golden fixture missing; run data-raw/generate_simd_goldens.R")
      with_simd(simd_enabled, {
        snd <- Sound(wav_path)
        harm <- snd$to_harmonicity_cc()
        golden <- read_golden_numeric(golden_path(fixture, "harmonicity"))

        expect_equal(harm$get_number_of_frames(), nrow(golden))

        hnr <- vapply(seq_len(nrow(golden)), function(i) {
          harm$get_value_at_time(golden$time[i], interpolation = "none")
        }, numeric(1))
        expect_equal(hnr, golden$hnr_db, tolerance = 1e-3)
      })
    })

    test_that(paste0("MFCC matches Praat.app golden (", fixture, ", ", label, ")"), {
      skip_if_not(file.exists(wav_path), "golden fixture missing; run data-raw/generate_simd_goldens.R")
      with_simd(simd_enabled, {
        snd <- Sound(wav_path)
        mfcc <- snd$to_mfcc(13, 0.025, 0.01, 100, 7800, 100)
        golden <- read_golden_numeric(golden_path(fixture, "mfcc"))

        expect_equal(mfcc$get_number_of_frames(), nrow(golden))

        for (col in c("c1", "c2", "c3")) {
          idx <- match(col, c("c1", "c2", "c3"))
          vals <- vapply(seq_len(nrow(golden)), function(i) {
            mfcc$get_value_in_frame(i, idx)
          }, numeric(1))
          expect_equal(vals, golden[[col]], tolerance = 1e-2)
        }
      })
    })

    test_that(paste0("Spectrogram matches Praat.app golden (", fixture, ", ", label, ")"), {
      skip_if_not(file.exists(wav_path), "golden fixture missing; run data-raw/generate_simd_goldens.R")
      with_simd(simd_enabled, {
        snd <- Sound(wav_path)
        spec <- snd$to_spectrogram()
        golden <- read_golden_numeric(golden_path(fixture, "spectrogram"))

        power <- vapply(seq_len(nrow(golden)), function(i) {
          spec$get_power_at(golden$time[i], golden$freq[i])
        }, numeric(1))
        # power spectral density spans orders of magnitude -- compare on a dB
        # scale so the tolerance is meaningful across the whole dynamic range.
        expect_equal(10 * log10(pmax(power, 1e-30)),
                     10 * log10(pmax(golden$power, 1e-30)),
                     tolerance = 1e-2)
      })
    })

    test_that(paste0("PowerCepstrogram CPPS matches Praat.app golden (", fixture, ", ", label, ")"), {
      skip_if_not(file.exists(wav_path), "golden fixture missing; run data-raw/generate_simd_goldens.R")
      with_simd(simd_enabled, {
        snd <- Sound(wav_path)
        pcep <- snd$to_powercepstrogram(60, 0.002, 5000, 50)
        cpps <- pcep$get_cpps(
          subtract_tilt = TRUE, time_averaging_window = 0.001,
          quefrency_averaging_window = 0.0005, pitch_floor = 60, pitch_ceiling = 333.3,
          delta_f0 = 0.05, interpolation = "parabolic",
          quefrency_range_start = 0.003, quefrency_range_end = 0.04,
          trend_line_type = "straight", fit_method = "least squares"
        )
        golden <- read_golden_numeric(golden_path(fixture, "cpps"))
        # "least squares" fit is deterministic but not bit-identical between
        # Praat and pladdrr's independent implementations of the fit; 0.01 dB
        # is well below anything that would indicate a real divergence.
        expect_equal(cpps, golden$cpps_db[1], tolerance = 0.01)
      })
    })

    test_that(paste0("Resample matches Praat.app golden (", fixture, ", ", label, ")"), {
      skip_if_not(file.exists(wav_path), "golden fixture missing; run data-raw/generate_simd_goldens.R")
      with_simd(simd_enabled, {
        snd <- Sound(wav_path)
        rs <- snd$resample(8000, 50)
        vals <- rs$get_values(channel = 1)
        golden <- read.csv(golden_path(fixture, "resample"))
        expect_equal(vals[golden$sample], golden$value, tolerance = 1e-3)
      })
    })

    test_that(paste0("Scale peak matches Praat.app golden (", fixture, ", ", label, ")"), {
      skip_if_not(file.exists(wav_path), "golden fixture missing; run data-raw/generate_simd_goldens.R")
      with_simd(simd_enabled, {
        snd <- Sound(wav_path)
        snd$scale_peak(0.99)
        vals <- snd$get_values(channel = 1)
        golden <- read.csv(golden_path(fixture, "scalepeak"))
        expect_equal(vals[golden$sample], golden$value, tolerance = 1e-6)
      })
    })

    test_that(paste0("Pre-emphasis matches Praat.app golden (", fixture, ", ", label, ")"), {
      skip_if_not(file.exists(wav_path), "golden fixture missing; run data-raw/generate_simd_goldens.R")
      with_simd(simd_enabled, {
        # Praat's scripting command "Pre-emphasize (in-place)" bundles a
        # Scale peak: 0.99 after the filter (see fon/praat_Sound.cpp);
        # pladdrr's pre_emphasize() matches the underlying filter alone
        # (Sound_preEmphasize_inplace), so chain scale_peak to compare like
        # for like.
        snd <- Sound(wav_path)
        snd$pre_emphasize(50)
        snd$scale_peak(0.99)
        vals <- snd$get_values(channel = 1)
        golden <- read.csv(golden_path(fixture, "preemphasis"))
        expect_equal(vals[golden$sample], golden$value, tolerance = 1e-6)
      })
    })
  }
}

# --- Stereo-to-mono conversion (separate fixture, sound_conversion_simd) ---
for (simd_enabled in c(FALSE, TRUE)) {
  label <- if (simd_enabled) "SIMD" else "scalar"

  test_that(paste0("Stereo-to-mono conversion matches Praat.app golden (", label, ")"), {
    stereo_wav <- file.path(fixture_dir, "stereo_test.wav")
    skip_if_not(file.exists(stereo_wav), "golden fixture missing; run data-raw/generate_simd_goldens.R")
    with_simd(simd_enabled, {
      snd <- Sound(stereo_wav)
      mono <- snd$convert_to_mono()
      vals <- mono$get_values(channel = 1)
      golden <- read.csv(file.path(fixture_dir, "stereo_test_mono_conversion_golden.csv"))
      expect_equal(vals[golden$sample], golden$value, tolerance = 1e-6)
    })
  })
}
