// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_pladdrr_RCPPEXPORTS_H_GEN_
#define RCPP_pladdrr_RCPPEXPORTS_H_GEN_

#include "pladdrr_types.h"
#include <Rcpp.h>

namespace pladdrr {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("pladdrr", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("pladdrr", "_pladdrr_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in pladdrr");
            }
        }
    }

    inline Rcpp::List _simd_info() {
        typedef SEXP(*Ptr__simd_info)();
        static Ptr__simd_info p__simd_info = NULL;
        if (p__simd_info == NULL) {
            validateSignature("Rcpp::List(*_simd_info)()");
            p__simd_info = (Ptr__simd_info)R_GetCCallable("pladdrr", "_pladdrr__simd_info");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p__simd_info();
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::List >(rcpp_result_gen);
    }

}

#endif // RCPP_pladdrr_RCPPEXPORTS_H_GEN_
