/*
 * Part of pladdrr: R interface to Praat
 *
 * Copyright (C) 2025 Fredrik Nylén
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
// module_init.cpp
// Rcpp Module initialization hook (pladdrr 2.0)
// Registers module boot symbols explicitly (CRAN-compliant)

#include <Rcpp.h>
#include <R_ext/Rdynload.h>
#include <vector>

// Declare all 38 module boot functions generated by RCPP_MODULE macro
extern "C" {
    SEXP _rcpp_module_boot_pitch_module();
    SEXP _rcpp_module_boot_sound_module();
    SEXP _rcpp_module_boot_formant_module();
    SEXP _rcpp_module_boot_intensity_module();
    SEXP _rcpp_module_boot_spectrum_module();
    SEXP _rcpp_module_boot_spectrogram_module();
    SEXP _rcpp_module_boot_harmonicity_module();
    SEXP _rcpp_module_boot_pitchtier_module();
    SEXP _rcpp_module_boot_intensitytier_module();
    SEXP _rcpp_module_boot_durationtier_module();
    SEXP _rcpp_module_boot_amplitudetier_module();
    SEXP _rcpp_module_boot_pointprocess_module();
    SEXP _rcpp_module_boot_ltas_module();
    SEXP _rcpp_module_boot_spectrumtier_module();
    SEXP _rcpp_module_boot_matrix_module();
    SEXP _rcpp_module_boot_cepstrum_module();
    SEXP _rcpp_module_boot_powercepstrum_module();
    SEXP _rcpp_module_boot_cochleagram_module();
    SEXP _rcpp_module_boot_excitation_module();
    SEXP _rcpp_module_boot_electroglottogram_module();
    SEXP _rcpp_module_boot_formantgrid_module();
    SEXP _rcpp_module_boot_formanttier_module();
    SEXP _rcpp_module_boot_vocaltract_module();
    SEXP _rcpp_module_boot_longsound_module();
    SEXP _rcpp_module_boot_lpc_module();
    SEXP _rcpp_module_boot_table_module();
    SEXP _rcpp_module_boot_textgrid_module();
    SEXP _rcpp_module_boot_manipulation_module();
    SEXP _rcpp_module_boot_polygon_module();
    SEXP _rcpp_module_boot_formantpath_module();
    SEXP _rcpp_module_boot_complexspectrogram_module();
    SEXP _rcpp_module_boot_klattgrid_module();
    SEXP _rcpp_module_boot_sound_operations_module();
    SEXP _rcpp_module_boot_interpreter_module();
    SEXP _rcpp_module_boot_mfcc_module();
    SEXP _rcpp_module_boot_pca_module();
    SEXP _rcpp_module_boot_formantmodeler_module();
    SEXP _rcpp_module_boot_discriminant_module();
    SEXP _rcpp_module_boot_dtw_module();
}

// Registration table for module boot symbols
// These are looked up by Rcpp::Module() via .Call()
static const R_CallMethodDef ModuleEntries[] = {
    {"_rcpp_module_boot_pitch_module",              (DL_FUNC) &_rcpp_module_boot_pitch_module,              0},
    {"_rcpp_module_boot_sound_module",              (DL_FUNC) &_rcpp_module_boot_sound_module,              0},
    {"_rcpp_module_boot_formant_module",            (DL_FUNC) &_rcpp_module_boot_formant_module,            0},
    {"_rcpp_module_boot_intensity_module",          (DL_FUNC) &_rcpp_module_boot_intensity_module,          0},
    {"_rcpp_module_boot_spectrum_module",           (DL_FUNC) &_rcpp_module_boot_spectrum_module,           0},
    {"_rcpp_module_boot_spectrogram_module",        (DL_FUNC) &_rcpp_module_boot_spectrogram_module,        0},
    {"_rcpp_module_boot_harmonicity_module",        (DL_FUNC) &_rcpp_module_boot_harmonicity_module,        0},
    {"_rcpp_module_boot_pitchtier_module",          (DL_FUNC) &_rcpp_module_boot_pitchtier_module,          0},
    {"_rcpp_module_boot_intensitytier_module",      (DL_FUNC) &_rcpp_module_boot_intensitytier_module,      0},
    {"_rcpp_module_boot_durationtier_module",       (DL_FUNC) &_rcpp_module_boot_durationtier_module,       0},
    {"_rcpp_module_boot_amplitudetier_module",      (DL_FUNC) &_rcpp_module_boot_amplitudetier_module,      0},
    {"_rcpp_module_boot_pointprocess_module",       (DL_FUNC) &_rcpp_module_boot_pointprocess_module,       0},
    {"_rcpp_module_boot_ltas_module",               (DL_FUNC) &_rcpp_module_boot_ltas_module,               0},
    {"_rcpp_module_boot_spectrumtier_module",       (DL_FUNC) &_rcpp_module_boot_spectrumtier_module,       0},
    {"_rcpp_module_boot_matrix_module",             (DL_FUNC) &_rcpp_module_boot_matrix_module,             0},
    {"_rcpp_module_boot_cepstrum_module",           (DL_FUNC) &_rcpp_module_boot_cepstrum_module,           0},
    {"_rcpp_module_boot_powercepstrum_module",      (DL_FUNC) &_rcpp_module_boot_powercepstrum_module,      0},
    {"_rcpp_module_boot_cochleagram_module",        (DL_FUNC) &_rcpp_module_boot_cochleagram_module,        0},
    {"_rcpp_module_boot_excitation_module",         (DL_FUNC) &_rcpp_module_boot_excitation_module,         0},
    {"_rcpp_module_boot_electroglottogram_module",  (DL_FUNC) &_rcpp_module_boot_electroglottogram_module,  0},
    {"_rcpp_module_boot_formantgrid_module",        (DL_FUNC) &_rcpp_module_boot_formantgrid_module,        0},
    {"_rcpp_module_boot_formanttier_module",        (DL_FUNC) &_rcpp_module_boot_formanttier_module,        0},
    {"_rcpp_module_boot_vocaltract_module",         (DL_FUNC) &_rcpp_module_boot_vocaltract_module,         0},
    {"_rcpp_module_boot_longsound_module",          (DL_FUNC) &_rcpp_module_boot_longsound_module,          0},
    {"_rcpp_module_boot_lpc_module",                (DL_FUNC) &_rcpp_module_boot_lpc_module,                0},
    {"_rcpp_module_boot_table_module",              (DL_FUNC) &_rcpp_module_boot_table_module,              0},
    {"_rcpp_module_boot_textgrid_module",           (DL_FUNC) &_rcpp_module_boot_textgrid_module,           0},
    {"_rcpp_module_boot_manipulation_module",       (DL_FUNC) &_rcpp_module_boot_manipulation_module,       0},
    {"_rcpp_module_boot_polygon_module",            (DL_FUNC) &_rcpp_module_boot_polygon_module,            0},
    {"_rcpp_module_boot_formantpath_module",        (DL_FUNC) &_rcpp_module_boot_formantpath_module,        0},
    {"_rcpp_module_boot_complexspectrogram_module",  (DL_FUNC) &_rcpp_module_boot_complexspectrogram_module, 0},
    {"_rcpp_module_boot_klattgrid_module",          (DL_FUNC) &_rcpp_module_boot_klattgrid_module,          0},
    {"_rcpp_module_boot_sound_operations_module",   (DL_FUNC) &_rcpp_module_boot_sound_operations_module,   0},
    {"_rcpp_module_boot_interpreter_module",        (DL_FUNC) &_rcpp_module_boot_interpreter_module,        0},
    {"_rcpp_module_boot_mfcc_module",               (DL_FUNC) &_rcpp_module_boot_mfcc_module,               0},
    {"_rcpp_module_boot_pca_module",                (DL_FUNC) &_rcpp_module_boot_pca_module,                0},
    {"_rcpp_module_boot_formantmodeler_module",     (DL_FUNC) &_rcpp_module_boot_formantmodeler_module,     0},
    {"_rcpp_module_boot_discriminant_module",       (DL_FUNC) &_rcpp_module_boot_discriminant_module,       0},
    {"_rcpp_module_boot_dtw_module",                (DL_FUNC) &_rcpp_module_boot_dtw_module,                0},
    {NULL, NULL, 0}
};

// [[Rcpp::init]]
void register_module_entries(DllInfo* dll) {
    // Build a combined registration table merging RcppExports' CallEntries
    // with our module boot entries. R_registerRoutines REPLACES the previous
    // registration, so we must include both in a single call.

    // Count CallEntries from RcppExports.cpp (extern, NULL-terminated)
    extern const R_CallMethodDef CallEntries[];
    int n_call = 0;
    while (CallEntries[n_call].name != NULL) n_call++;

    // Count ModuleEntries (NULL-terminated)
    int n_mod = 0;
    while (ModuleEntries[n_mod].name != NULL) n_mod++;

    // Allocate combined table (+1 for NULL sentinel). Must be static:
    // R_registerRoutines stores this pointer in dll->CallEntries and keeps
    // reading it for the life of the DLL, past this function's return.
    static std::vector<R_CallMethodDef> combined(n_call + n_mod + 1);
    for (int i = 0; i < n_call; i++) combined[i] = CallEntries[i];
    for (int i = 0; i < n_mod; i++) combined[n_call + i] = ModuleEntries[i];
    combined[n_call + n_mod] = {NULL, NULL, 0};

    R_registerRoutines(dll, NULL, combined.data(), NULL, NULL);
}
