// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// praat_version
String praat_version();
RcppExport SEXP _speaker_praat_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(praat_version());
    return rcpp_result_gen;
END_RCPP
}
// sound_stats
List sound_stats(NumericVector sound_data);
RcppExport SEXP _speaker_sound_stats(SEXP sound_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type sound_data(sound_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(sound_stats(sound_data));
    return rcpp_result_gen;
END_RCPP
}
// create_sound
List create_sound(NumericVector values, double sampling_frequency);
RcppExport SEXP _speaker_create_sound(SEXP valuesSEXP, SEXP sampling_frequencySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< double >::type sampling_frequency(sampling_frequencySEXP);
    rcpp_result_gen = Rcpp::wrap(create_sound(values, sampling_frequency));
    return rcpp_result_gen;
END_RCPP
}
// get_sound_duration
double get_sound_duration(List sound_object);
RcppExport SEXP _speaker_get_sound_duration(SEXP sound_objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type sound_object(sound_objectSEXP);
    rcpp_result_gen = Rcpp::wrap(get_sound_duration(sound_object));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_speaker_praat_version", (DL_FUNC) &_speaker_praat_version, 0},
    {"_speaker_sound_stats", (DL_FUNC) &_speaker_sound_stats, 1},
    {"_speaker_create_sound", (DL_FUNC) &_speaker_create_sound, 2},
    {"_speaker_get_sound_duration", (DL_FUNC) &_speaker_get_sound_duration, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_speaker(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
