// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// praat_version
String praat_version();
RcppExport SEXP _speaker_praat_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(praat_version());
    return rcpp_result_gen;
END_RCPP
}
// praat_initialize
bool praat_initialize();
RcppExport SEXP _speaker_praat_initialize() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(praat_initialize());
    return rcpp_result_gen;
END_RCPP
}
// sound_stats
List sound_stats(NumericVector sound_data);
RcppExport SEXP _speaker_sound_stats(SEXP sound_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type sound_data(sound_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(sound_stats(sound_data));
    return rcpp_result_gen;
END_RCPP
}
// create_sound_from_values
List create_sound_from_values(NumericVector values, double sampling_rate, double start_time);
RcppExport SEXP _speaker_create_sound_from_values(SEXP valuesSEXP, SEXP sampling_rateSEXP, SEXP start_timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< double >::type sampling_rate(sampling_rateSEXP);
    Rcpp::traits::input_parameter< double >::type start_time(start_timeSEXP);
    rcpp_result_gen = Rcpp::wrap(create_sound_from_values(values, sampling_rate, start_time));
    return rcpp_result_gen;
END_RCPP
}
// get_sound_duration_cpp
double get_sound_duration_cpp(List sound_obj);
RcppExport SEXP _speaker_get_sound_duration_cpp(SEXP sound_objSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type sound_obj(sound_objSEXP);
    rcpp_result_gen = Rcpp::wrap(get_sound_duration_cpp(sound_obj));
    return rcpp_result_gen;
END_RCPP
}
// get_sound_sampling_rate_cpp
double get_sound_sampling_rate_cpp(List sound_obj);
RcppExport SEXP _speaker_get_sound_sampling_rate_cpp(SEXP sound_objSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type sound_obj(sound_objSEXP);
    rcpp_result_gen = Rcpp::wrap(get_sound_sampling_rate_cpp(sound_obj));
    return rcpp_result_gen;
END_RCPP
}
// get_sound_n_samples_cpp
int get_sound_n_samples_cpp(List sound_obj);
RcppExport SEXP _speaker_get_sound_n_samples_cpp(SEXP sound_objSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type sound_obj(sound_objSEXP);
    rcpp_result_gen = Rcpp::wrap(get_sound_n_samples_cpp(sound_obj));
    return rcpp_result_gen;
END_RCPP
}
// praat_error_to_r
void praat_error_to_r(const std::string& error_msg);
RcppExport SEXP _speaker_praat_error_to_r(SEXP error_msgSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type error_msg(error_msgSEXP);
    praat_error_to_r(error_msg);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_speaker_praat_version", (DL_FUNC) &_speaker_praat_version, 0},
    {"_speaker_praat_initialize", (DL_FUNC) &_speaker_praat_initialize, 0},
    {"_speaker_sound_stats", (DL_FUNC) &_speaker_sound_stats, 1},
    {"_speaker_create_sound_from_values", (DL_FUNC) &_speaker_create_sound_from_values, 3},
    {"_speaker_get_sound_duration_cpp", (DL_FUNC) &_speaker_get_sound_duration_cpp, 1},
    {"_speaker_get_sound_sampling_rate_cpp", (DL_FUNC) &_speaker_get_sound_sampling_rate_cpp, 1},
    {"_speaker_get_sound_n_samples_cpp", (DL_FUNC) &_speaker_get_sound_n_samples_cpp, 1},
    {"_speaker_praat_error_to_r", (DL_FUNC) &_speaker_praat_error_to_r, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_speaker(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
