# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.autocorrelation_simd <- function(data, max_lag) {
    .Call(`_pladdrr_autocorrelation_simd`, data, max_lag)
}

.autocorrelation_normalized_simd <- function(data, max_lag) {
    .Call(`_pladdrr_autocorrelation_normalized_simd`, data, max_lag)
}

.cross_correlation_simd <- function(x, y) {
    .Call(`_pladdrr_cross_correlation_simd`, x, y)
}

.windowed_autocorrelation_simd <- function(data, frame_length, max_lag, hop_size) {
    .Call(`_pladdrr_windowed_autocorrelation_simd`, data, frame_length, max_lag, hop_size)
}

.lpc_autocorrelation_simd <- function(data, num_coefficients) {
    .Call(`_pladdrr_lpc_autocorrelation_simd`, data, num_coefficients)
}

.autocorrelation_scalar <- function(data, max_lag) {
    .Call(`_pladdrr_autocorrelation_scalar`, data, max_lag)
}

.autocorrelation_normalized_scalar <- function(data, max_lag) {
    .Call(`_pladdrr_autocorrelation_normalized_scalar`, data, max_lag)
}

.cross_correlation_scalar <- function(x, y) {
    .Call(`_pladdrr_cross_correlation_scalar`, x, y)
}

.windowed_autocorrelation_scalar <- function(data, frame_length, max_lag, hop_size) {
    .Call(`_pladdrr_windowed_autocorrelation_scalar`, data, frame_length, max_lag, hop_size)
}

.lpc_autocorrelation_scalar <- function(data, num_coefficients) {
    .Call(`_pladdrr_lpc_autocorrelation_scalar`, data, num_coefficients)
}

.autocorrelation <- function(data, max_lag) {
    .Call(`_pladdrr_autocorrelation`, data, max_lag)
}

.autocorrelation_normalized <- function(data, max_lag) {
    .Call(`_pladdrr_autocorrelation_normalized`, data, max_lag)
}

.cross_correlation <- function(x, y) {
    .Call(`_pladdrr_cross_correlation`, x, y)
}

.windowed_autocorrelation <- function(data, frame_length, max_lag, hop_size) {
    .Call(`_pladdrr_windowed_autocorrelation`, data, frame_length, max_lag, hop_size)
}

.lpc_autocorrelation <- function(data, num_coefficients) {
    .Call(`_pladdrr_lpc_autocorrelation`, data, num_coefficients)
}

#' SIMD-optimized RMS calculation
#' @keywords internal
.sound_get_rms_simd <- function(xptr, from_time, to_time) {
    .Call(`_pladdrr_sound_get_rms_simd`, xptr, from_time, to_time)
}

#' SIMD-optimized energy calculation
#' @keywords internal
.sound_get_energy_simd <- function(xptr, from_time, to_time) {
    .Call(`_pladdrr_sound_get_energy_simd`, xptr, from_time, to_time)
}

#' SIMD-optimized power calculation
#' @keywords internal
.sound_get_power_simd <- function(xptr, from_time, to_time) {
    .Call(`_pladdrr_sound_get_power_simd`, xptr, from_time, to_time)
}

.praat_interpreter_init <- function() {
    invisible(.Call(`_pladdrr_praat_interpreter_init`))
}

.praat_is_initialized <- function() {
    .Call(`_pladdrr_praat_is_initialized`)
}

.praat_run_script <- function(script_text) {
    invisible(.Call(`_pladdrr_praat_run_script`, script_text))
}

.praat_evaluate_numeric <- function(expression) {
    .Call(`_pladdrr_praat_evaluate_numeric`, expression)
}

.praat_evaluate_string <- function(expression) {
    .Call(`_pladdrr_praat_evaluate_string`, expression)
}

.praat_evaluate_vector <- function(expression) {
    .Call(`_pladdrr_praat_evaluate_vector`, expression)
}

.praat_evaluate_matrix <- function(expression) {
    .Call(`_pladdrr_praat_evaluate_matrix`, expression)
}

.praat_evaluate_string_array <- function(expression) {
    .Call(`_pladdrr_praat_evaluate_string_array`, expression)
}

.praat_interpreter_create <- function() {
    .Call(`_pladdrr_praat_interpreter_create`)
}

.praat_interpreter_run <- function(xptr, script) {
    invisible(.Call(`_pladdrr_praat_interpreter_run`, xptr, script))
}

.praat_interpreter_get_variable <- function(xptr, name) {
    .Call(`_pladdrr_praat_interpreter_get_variable`, xptr, name)
}

.praat_interpreter_set_variable <- function(xptr, name, value) {
    invisible(.Call(`_pladdrr_praat_interpreter_set_variable`, xptr, name, value))
}

.praat_interpreter_eval_numeric <- function(xptr, expression) {
    .Call(`_pladdrr_praat_interpreter_eval_numeric`, xptr, expression)
}

.praat_interpreter_eval_string <- function(xptr, expression) {
    .Call(`_pladdrr_praat_interpreter_eval_string`, xptr, expression)
}

.praat_interpreter_eval_vector <- function(xptr, expression) {
    .Call(`_pladdrr_praat_interpreter_eval_vector`, xptr, expression)
}

.praat_interpreter_eval_matrix <- function(xptr, expression) {
    .Call(`_pladdrr_praat_interpreter_eval_matrix`, xptr, expression)
}

.praat_interpreter_eval_string_array <- function(xptr, expression) {
    .Call(`_pladdrr_praat_interpreter_eval_string_array`, xptr, expression)
}

.praat_interpreter_object_count <- function() {
    .Call(`_pladdrr_praat_interpreter_object_count`)
}

.praat_interpreter_list_objects <- function() {
    .Call(`_pladdrr_praat_interpreter_list_objects`)
}

#' Get object from Praat object list by name
#' @param name Object name (e.g., "Sound mySound" or just "mySound")
#' @param expected_type Expected class name (e.g., "Sound"), or empty for any
#' @return External pointer to the Praat object (copy)
#' @keywords internal
.praat_interpreter_get_object <- function(name, expected_type) {
    .Call(`_pladdrr_praat_interpreter_get_object`, name, expected_type)
}

#' Get object by ID from Praat object list
#' @param id Object ID number
#' @return External pointer to the Praat object (copy)
#' @keywords internal
.praat_interpreter_get_object_by_id <- function(id) {
    .Call(`_pladdrr_praat_interpreter_get_object_by_id`, id)
}

#' Add R object to Praat object list
#' @param xptr External pointer to Praat object (will be copied)
#' @param name Name for the object in Praat's list
#' @param class_name Class name (e.g., "Sound", "Pitch")
#' @return ID of the newly added object
#' @keywords internal
.praat_interpreter_set_object <- function(xptr, name, class_name) {
    .Call(`_pladdrr_praat_interpreter_set_object`, xptr, name, class_name)
}

#' Remove object from Praat object list by name
#' @param name Object name
#' @keywords internal
.praat_interpreter_remove_object <- function(name) {
    invisible(.Call(`_pladdrr_praat_interpreter_remove_object`, name))
}

#' Remove object from Praat object list by ID
#' @param id Object ID
#' @keywords internal
.praat_interpreter_remove_object_by_id <- function(id) {
    invisible(.Call(`_pladdrr_praat_interpreter_remove_object_by_id`, id))
}

#' Select object in Praat object list by name
#' @param name Object name
#' @param add If TRUE, add to selection; if FALSE, replace selection
#' @keywords internal
.praat_interpreter_select_object <- function(name, add = FALSE) {
    invisible(.Call(`_pladdrr_praat_interpreter_select_object`, name, add))
}

#' Clear all objects from Praat object list
#' @keywords internal
.praat_interpreter_clear_objects <- function() {
    invisible(.Call(`_pladdrr_praat_interpreter_clear_objects`))
}

.euclidean_distance_simd <- function(x, y) {
    .Call(`_pladdrr_euclidean_distance`, x, y)
}

.cosine_similarity_simd <- function(x, y) {
    .Call(`_pladdrr_cosine_similarity`, x, y)
}

.matrix_multiply_rows_simd <- function(x, v) {
    invisible(.Call(`_pladdrr_r_matrix_multiply_rows`, x, v))
}

.dot_product_simd <- function(x, y) {
    .Call(`_pladdrr_r_dot_product`, x, y)
}

.axpy_simd <- function(alpha, x, y) {
    invisible(.Call(`_pladdrr_r_axpy`, alpha, x, y))
}

.subtract_linear_trend_simd <- function(frequencies, times) {
    .Call(`_pladdrr_subtract_linear_trend`, frequencies, times)
}

.subtract_mean_simd <- function(data) {
    .Call(`_pladdrr_subtract_mean`, data)
}

#' Get Praat version information
#'
#' Returns the version string for the Praat library integration
#'
#' @return Character string with version information
#' @export
praat_version <- function() {
    .Call(`_pladdrr_praat_version`)
}

#' Initialize Praat library
#'
#' Performs any necessary initialization for Praat components
#' This should be called when the package is loaded
#'
#' @return Logical indicating success
#' @keywords internal
praat_initialize <- function() {
    .Call(`_pladdrr_praat_initialize`)
}

.test_class_registry <- function() {
    .Call(`_pladdrr_test_class_registry`)
}

#' Calculate basic sound statistics
#'
#' Calculates basic statistics for a sound vector
#'
#' @param sound_data Numeric vector containing sound amplitude values
#' @return List containing mean, min, max, and length statistics
#' @keywords internal
sound_stats <- function(sound_data) {
    .Call(`_pladdrr_sound_stats`, sound_data)
}

#' Create a sound object from numeric vector
#'
#' Creates a praat_sound object structure from R numeric data
#'
#' @param values Numeric vector of sound amplitude values
#' @param sampling_rate Sampling rate in Hz (default: 44100)
#' @param start_time Start time in seconds (default: 0.0)
#' @return List representing a praat_sound object with values and metadata
#' @export
create_sound_from_values <- function(values, sampling_rate = 44100.0, start_time = 0.0) {
    .Call(`_pladdrr_create_sound_from_values`, values, sampling_rate, start_time)
}

#' Get sound duration
#'
#' Extract the duration of a sound object in seconds
#'
#' @param sound_obj List representing a praat_sound object
#' @return Numeric value representing duration in seconds
#' @keywords internal
get_sound_duration_cpp <- function(sound_obj) {
    .Call(`_pladdrr_get_sound_duration_cpp`, sound_obj)
}

#' Get sound sampling rate
#'
#' Extract the sampling rate of a sound object
#'
#' @param sound_obj List representing a praat_sound object
#' @return Numeric value representing sampling rate in Hz
#' @keywords internal
get_sound_sampling_rate_cpp <- function(sound_obj) {
    .Call(`_pladdrr_get_sound_sampling_rate_cpp`, sound_obj)
}

#' Get number of samples in sound
#'
#' Extract the number of samples in a sound object
#'
#' @param sound_obj List representing a praat_sound object
#' @return Integer number of samples
#' @keywords internal
get_sound_n_samples_cpp <- function(sound_obj) {
    .Call(`_pladdrr_get_sound_n_samples_cpp`, sound_obj)
}

#' Get SIMD capabilities (internal)
#' @keywords internal
.simd_info <- function() {
    .Call(`_pladdrr_simd_info`)
}

.sound_convert_to_mono_simd <- function(xptr) {
    .Call(`_pladdrr_sound_convert_to_mono_simd`, xptr)
}

.complex_multiply_simd <- function(a, b) {
    .Call(`_pladdrr_complex_multiply`, a, b)
}

#' SIMD-optimized sound scaling (peak amplitude)
#' @keywords internal
.sound_scale_peak_simd <- function(xptr, new_peak) {
    invisible(.Call(`_pladdrr_sound_scale_peak_simd`, xptr, new_peak))
}

#' SIMD-optimized sound mixing with balance
#' @keywords internal
.sound_mix_simd <- function(xptr1, xptr2, balance) {
    .Call(`_pladdrr_sound_mix_simd`, xptr1, xptr2, balance)
}

.sound_get_statistics_simd <- function(xptr) {
    .Call(`_pladdrr_sound_get_statistics`, xptr)
}

#' Get a single sample from Sound (no copy)
#' @param xptr External pointer to Sound
#' @param channel Channel number (1-based)
#' @param sample Sample index (1-based)
#' @return Sample value
.sound_get_sample <- function(xptr, channel, sample) {
    .Call(`_pladdrr_sound_get_sample`, xptr, channel, sample)
}

#' Set a single sample in Sound (in-place modification)
#' @param xptr External pointer to Sound
#' @param channel Channel number (1-based)
#' @param sample Sample index (1-based)
#' @param value New sample value
.sound_set_sample <- function(xptr, channel, sample, value) {
    invisible(.Call(`_pladdrr_sound_set_sample`, xptr, channel, sample, value))
}

#' Get a range of samples from Sound (minimal copy)
#' @param xptr External pointer to Sound
#' @param channel Channel number (1-based)
#' @param from_sample Start sample (1-based, inclusive)
#' @param to_sample End sample (1-based, inclusive)
#' @return Numeric vector of samples
.sound_get_samples_range <- function(xptr, channel, from_sample, to_sample) {
    .Call(`_pladdrr_sound_get_samples_range`, xptr, channel, from_sample, to_sample)
}

#' Set a range of samples in Sound (in-place modification)
#' @param xptr External pointer to Sound
#' @param channel Channel number (1-based)
#' @param from_sample Start sample (1-based, inclusive)
#' @param values Numeric vector of new values
.sound_set_samples_range <- function(xptr, channel, from_sample, values) {
    invisible(.Call(`_pladdrr_sound_set_samples_range`, xptr, channel, from_sample, values))
}

#' Get samples at specific time points (vectorized)
#' @param xptr External pointer to Sound
#' @param channel Channel number (1-based)
#' @param times Numeric vector of time points
#' @param interpolation 0=nearest, 1=linear, 2=cubic, 3=sinc70, 4=sinc700
#' @return Numeric vector of sample values
.sound_get_values_at_times <- function(xptr, channel, times, interpolation) {
    .Call(`_pladdrr_sound_get_values_at_times`, xptr, channel, times, interpolation)
}

#' Scale samples in-place (no copy)
#' @param xptr External pointer to Sound
#' @param factor Scale factor
.sound_scale_inplace <- function(xptr, factor) {
    invisible(.Call(`_pladdrr_sound_scale_inplace`, xptr, factor))
}

#' Add value to all samples in-place
#' @param xptr External pointer to Sound
#' @param value Value to add
.sound_add_inplace <- function(xptr, value) {
    invisible(.Call(`_pladdrr_sound_add_inplace`, xptr, value))
}

#' Apply gain in dB in-place
#' @param xptr External pointer to Sound
#' @param gain_db Gain in decibels
.sound_apply_gain_db_inplace <- function(xptr, gain_db) {
    invisible(.Call(`_pladdrr_sound_apply_gain_db_inplace`, xptr, gain_db))
}

#' Normalize peak to value in-place
#' @param xptr External pointer to Sound
#' @param peak_value Target peak value (default 0.99)
.sound_normalize_peak_inplace <- function(xptr, peak_value) {
    invisible(.Call(`_pladdrr_sound_normalize_peak_inplace`, xptr, peak_value))
}

#' Apply function to overlapping windows (zero-copy windowed processing)
#' @param xptr External pointer to Sound
#' @param channel Channel number (1-based)
#' @param window_size Window size in samples
#' @param hop_size Hop size in samples
#' @return Matrix with one column per window
.sound_get_windows <- function(xptr, channel, window_size, hop_size) {
    .Call(`_pladdrr_sound_get_windows`, xptr, channel, window_size, hop_size)
}

#' Get Sound info without copying samples
#' @param xptr External pointer to Sound
#' @return List with sound properties
.sound_info <- function(xptr) {
    .Call(`_pladdrr_sound_info`, xptr)
}

#' Safe error wrapper for Praat calls
#'
#' Provides a consistent error handling pattern for Praat operations
#'
#' @param context Description of what operation failed
#' @keywords internal
NULL

#' Validate positive numeric parameter
#'
#' Ensures a numeric parameter is positive (> 0)
#'
#' @param value The value to check
#' @param param_name Name of the parameter for error messages
#' @keywords internal
NULL

#' Validate non-negative numeric parameter
#'
#' Ensures a numeric parameter is non-negative (>= 0)
#'
#' @param value The value to check
#' @param param_name Name of the parameter for error messages
#' @keywords internal
NULL

#' Validate numeric parameter is in range
#'
#' Ensures a numeric parameter falls within a specified range
#'
#' @param value The value to check
#' @param min_val Minimum allowed value (inclusive)
#' @param max_val Maximum allowed value (inclusive)
#' @param param_name Name of the parameter for error messages
#' @keywords internal
NULL

#' Validate integer parameter is positive
#'
#' Ensures an integer parameter is positive (> 0)
#'
#' @param value The value to check
#' @param param_name Name of the parameter for error messages
#' @keywords internal
NULL

#' Validate that an R list represents a valid sound object
#'
#' Checks that a list contains the required fields for a praat_sound object
#'
#' @param sound_obj R list representing a sound object
#' @return true if valid, throws error if invalid
#' @keywords internal
NULL

#' Validate that an R list represents a valid pitch object
#'
#' Checks that a list contains the required fields for a praat_pitch object
#'
#' @param pitch_obj R list representing a pitch object
#' @return true if valid, throws error if invalid
#' @keywords internal
NULL

#' Convert R logical to C++ bool with NA handling
#'
#' Safely converts R logical values to C++ bool, handling NA as false
#'
#' @param x R logical value
#' @param default_val Default value if NA
#' @return bool value
#' @keywords internal
NULL

#' Convert R numeric to C++ double with NA handling
#'
#' Safely converts R numeric values to C++ double
#'
#' @param x R numeric value
#' @return double value (returns R_NaN if NA)
#' @keywords internal
NULL

#' Convert Praat errors to R exceptions
#'
#' Wraps Praat function calls and converts Praat's error system to R exceptions
#'
#' @param error_msg Error message from Praat
#' @keywords internal
praat_error_to_r <- function(error_msg) {
    invisible(.Call(`_pladdrr_praat_error_to_r`, error_msg))
}

#' Compute jitter metrics from period array (SIMD-optimized)
#' @param periods Numeric vector of period durations
#' @return List with jitter_local, jitter_local_absolute, jitter_rap, jitter_ppq5, jitter_ddp
.jitter_from_periods_simd <- function(periods) {
    .Call(`_pladdrr_jitter_from_periods_simd`, periods)
}

#' Compute shimmer metrics from amplitude array (SIMD-optimized)
#' @param amplitudes Numeric vector of peak amplitudes per period
#' @return List with shimmer_local, shimmer_local_db, shimmer_apq3, shimmer_apq5, shimmer_apq11, shimmer_dda
.shimmer_from_amplitudes_simd <- function(amplitudes) {
    .Call(`_pladdrr_shimmer_from_amplitudes_simd`, amplitudes)
}

#' Compute complete voice quality metrics from periods and amplitudes
#' @param periods Numeric vector of period durations
#' @param amplitudes Numeric vector of peak amplitudes per period
#' @return List with all jitter and shimmer metrics
.voice_quality_metrics_simd <- function(periods, amplitudes) {
    .Call(`_pladdrr_voice_quality_metrics_simd`, periods, amplitudes)
}

.apply_hamming_window_simd <- function(data) {
    .Call(`_pladdrr_apply_hamming_window_simd`, data)
}

.apply_hanning_window_simd <- function(data) {
    .Call(`_pladdrr_apply_hanning_window_simd`, data)
}

.apply_gaussian_window_simd <- function(data, sigma = 0.4) {
    .Call(`_pladdrr_apply_gaussian_window_simd`, data, sigma)
}

.apply_hamming_window_scalar <- function(data) {
    .Call(`_pladdrr_apply_hamming_window_scalar`, data)
}

.apply_hanning_window_scalar <- function(data) {
    .Call(`_pladdrr_apply_hanning_window_scalar`, data)
}

.apply_gaussian_window_scalar <- function(data, sigma = 0.4) {
    .Call(`_pladdrr_apply_gaussian_window_scalar`, data, sigma)
}

.apply_hamming_window <- function(data) {
    .Call(`_pladdrr_apply_hamming_window`, data)
}

.apply_hanning_window <- function(data) {
    .Call(`_pladdrr_apply_hanning_window`, data)
}

.apply_gaussian_window <- function(data, sigma = 0.4) {
    .Call(`_pladdrr_apply_gaussian_window`, data, sigma)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_pladdrr_RcppExport_registerCCallable`)
})
