# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.durationtier_create <- function(tmin, tmax) {
    .Call(`_speaker_durationtier_create`, tmin, tmax)
}

.durationtier_get_start_time <- function(tier) {
    .Call(`_speaker_durationtier_get_start_time`, tier)
}

.durationtier_get_end_time <- function(tier) {
    .Call(`_speaker_durationtier_get_end_time`, tier)
}

.durationtier_get_number_of_points <- function(tier) {
    .Call(`_speaker_durationtier_get_number_of_points`, tier)
}

.durationtier_get_time_from_index <- function(tier, index) {
    .Call(`_speaker_durationtier_get_time_from_index`, tier, index)
}

.durationtier_get_value_at_index <- function(tier, index) {
    .Call(`_speaker_durationtier_get_value_at_index`, tier, index)
}

.durationtier_get_value_at_time <- function(tier, time) {
    .Call(`_speaker_durationtier_get_value_at_time`, tier, time)
}

.durationtier_add_point <- function(tier, time, value) {
    invisible(.Call(`_speaker_durationtier_add_point`, tier, time, value))
}

.durationtier_remove_point <- function(tier, index) {
    invisible(.Call(`_speaker_durationtier_remove_point`, tier, index))
}

.durationtier_save <- function(tier, path) {
    invisible(.Call(`_speaker_durationtier_save`, tier, path))
}

.durationtier_read <- function(path) {
    .Call(`_speaker_durationtier_read`, path)
}

.formant_from_sound_burg <- function(sound, time_step, max_number_of_formants, maximum_formant, window_length, pre_emphasis_from) {
    .Call(`_speaker_formant_from_sound_burg`, sound, time_step, max_number_of_formants, maximum_formant, window_length, pre_emphasis_from)
}

.formant_from_sound_keepall <- function(sound, time_step, max_number_of_formants, maximum_formant, window_length, pre_emphasis_from) {
    .Call(`_speaker_formant_from_sound_keepall`, sound, time_step, max_number_of_formants, maximum_formant, window_length, pre_emphasis_from)
}

.formant_get_number_of_frames <- function(formant) {
    .Call(`_speaker_formant_get_number_of_frames`, formant)
}

.formant_get_time_step <- function(formant) {
    .Call(`_speaker_formant_get_time_step`, formant)
}

.formant_get_min_num_formants <- function(formant) {
    .Call(`_speaker_formant_get_min_num_formants`, formant)
}

.formant_get_max_num_formants <- function(formant) {
    .Call(`_speaker_formant_get_max_num_formants`, formant)
}

.formant_get_value_at_time <- function(formant, formant_number, time, unit) {
    .Call(`_speaker_formant_get_value_at_time`, formant, formant_number, time, unit)
}

.formant_get_bandwidth_at_time <- function(formant, formant_number, time, unit) {
    .Call(`_speaker_formant_get_bandwidth_at_time`, formant, formant_number, time, unit)
}

.formant_get_mean <- function(formant, formant_number, from_time, to_time, unit) {
    .Call(`_speaker_formant_get_mean`, formant, formant_number, from_time, to_time, unit)
}

.formant_get_standard_deviation <- function(formant, formant_number, from_time, to_time, unit) {
    .Call(`_speaker_formant_get_standard_deviation`, formant, formant_number, from_time, to_time, unit)
}

.formant_get_quantile <- function(formant, formant_number, quantile, from_time, to_time, unit) {
    .Call(`_speaker_formant_get_quantile`, formant, formant_number, quantile, from_time, to_time, unit)
}

.formant_get_minimum <- function(formant, formant_number, from_time, to_time, unit, interpolate) {
    .Call(`_speaker_formant_get_minimum`, formant, formant_number, from_time, to_time, unit, interpolate)
}

.formant_get_maximum <- function(formant, formant_number, from_time, to_time, unit, interpolate) {
    .Call(`_speaker_formant_get_maximum`, formant, formant_number, from_time, to_time, unit, interpolate)
}

.formant_get_time_of_minimum <- function(formant, formant_number, from_time, to_time, unit, interpolate) {
    .Call(`_speaker_formant_get_time_of_minimum`, formant, formant_number, from_time, to_time, unit, interpolate)
}

.formant_get_time_of_maximum <- function(formant, formant_number, from_time, to_time, unit, interpolate) {
    .Call(`_speaker_formant_get_time_of_maximum`, formant, formant_number, from_time, to_time, unit, interpolate)
}

.formant_as_data_frame <- function(formant, max_formants) {
    .Call(`_speaker_formant_as_data_frame`, formant, max_formants)
}

.formant_save <- function(formant, path) {
    invisible(.Call(`_speaker_formant_save`, formant, path))
}

.harmonicity_to_sound_ac <- function(sound_xptr, time_step, min_pitch, silence_threshold, periods_per_window) {
    .Call(`_speaker_harmonicity_from_sound_ac`, sound_xptr, time_step, min_pitch, silence_threshold, periods_per_window)
}

.harmonicity_to_sound_cc <- function(sound_xptr, time_step, min_pitch, silence_threshold, periods_per_window) {
    .Call(`_speaker_harmonicity_from_sound_cc`, sound_xptr, time_step, min_pitch, silence_threshold, periods_per_window)
}

.harmonicity_get_value_at_time <- function(harmonicity_xptr, time, interpolation_type) {
    .Call(`_speaker_harmonicity_get_value_at_time`, harmonicity_xptr, time, interpolation_type)
}

.harmonicity_get_mean <- function(harmonicity_xptr, from_time, to_time) {
    .Call(`_speaker_harmonicity_get_mean`, harmonicity_xptr, from_time, to_time)
}

.harmonicity_get_minimum <- function(harmonicity_xptr, from_time, to_time, interpolation_type) {
    .Call(`_speaker_harmonicity_get_minimum`, harmonicity_xptr, from_time, to_time, interpolation_type)
}

.harmonicity_get_maximum <- function(harmonicity_xptr, from_time, to_time, interpolation_type) {
    .Call(`_speaker_harmonicity_get_maximum`, harmonicity_xptr, from_time, to_time, interpolation_type)
}

.harmonicity_get_standard_deviation <- function(harmonicity_xptr, from_time, to_time) {
    .Call(`_speaker_harmonicity_get_standard_deviation`, harmonicity_xptr, from_time, to_time)
}

.harmonicity_get_time_of_minimum <- function(harmonicity_xptr, from_time, to_time, interpolation_type) {
    .Call(`_speaker_harmonicity_get_time_of_minimum`, harmonicity_xptr, from_time, to_time, interpolation_type)
}

.harmonicity_get_time_of_maximum <- function(harmonicity_xptr, from_time, to_time, interpolation_type) {
    .Call(`_speaker_harmonicity_get_time_of_maximum`, harmonicity_xptr, from_time, to_time, interpolation_type)
}

.harmonicity_as_matrix <- function(harmonicity_xptr) {
    .Call(`_speaker_harmonicity_as_matrix`, harmonicity_xptr)
}

.harmonicity_get_number_of_frames <- function(harmonicity_xptr) {
    .Call(`_speaker_harmonicity_get_number_of_frames`, harmonicity_xptr)
}

.harmonicity_get_time_step <- function(harmonicity_xptr) {
    .Call(`_speaker_harmonicity_get_time_step`, harmonicity_xptr)
}

.harmonicity_get_start_time <- function(harmonicity_xptr) {
    .Call(`_speaker_harmonicity_get_start_time`, harmonicity_xptr)
}

.harmonicity_get_end_time <- function(harmonicity_xptr) {
    .Call(`_speaker_harmonicity_get_end_time`, harmonicity_xptr)
}

.intensity_get_value_at_time <- function(intensity_xptr, time, interpolation_type) {
    .Call(`_speaker_intensity_get_value_at_time`, intensity_xptr, time, interpolation_type)
}

.intensity_get_mean <- function(intensity_xptr, from_time, to_time) {
    .Call(`_speaker_intensity_get_mean`, intensity_xptr, from_time, to_time)
}

.intensity_get_minimum <- function(intensity_xptr, from_time, to_time) {
    .Call(`_speaker_intensity_get_minimum`, intensity_xptr, from_time, to_time)
}

.intensity_get_maximum <- function(intensity_xptr, from_time, to_time) {
    .Call(`_speaker_intensity_get_maximum`, intensity_xptr, from_time, to_time)
}

.intensity_get_standard_deviation <- function(intensity_xptr, from_time, to_time) {
    .Call(`_speaker_intensity_get_standard_deviation`, intensity_xptr, from_time, to_time)
}

.intensity_get_quantile <- function(intensity_xptr, from_time, to_time, quantile) {
    .Call(`_speaker_intensity_get_quantile`, intensity_xptr, from_time, to_time, quantile)
}

.intensity_get_time_of_minimum <- function(intensity_xptr, from_time, to_time) {
    .Call(`_speaker_intensity_get_time_of_minimum`, intensity_xptr, from_time, to_time)
}

.intensity_get_time_of_maximum <- function(intensity_xptr, from_time, to_time) {
    .Call(`_speaker_intensity_get_time_of_maximum`, intensity_xptr, from_time, to_time)
}

.intensity_get_time_from_frame <- function(intensity_xptr, frame) {
    .Call(`_speaker_intensity_get_time_from_frame`, intensity_xptr, frame)
}

.intensity_get_frame_from_time <- function(intensity_xptr, time) {
    .Call(`_speaker_intensity_get_frame_from_time`, intensity_xptr, time)
}

.intensity_get_number_of_frames <- function(intensity_xptr) {
    .Call(`_speaker_intensity_get_number_of_frames`, intensity_xptr)
}

.intensity_get_sampling_period <- function(intensity_xptr) {
    .Call(`_speaker_intensity_get_sampling_period`, intensity_xptr)
}

.intensity_get_start_time <- function(intensity_xptr) {
    .Call(`_speaker_intensity_get_start_time`, intensity_xptr)
}

.intensity_get_end_time <- function(intensity_xptr) {
    .Call(`_speaker_intensity_get_end_time`, intensity_xptr)
}

.intensity_down_to_intensity_tier <- function(intensity_xptr) {
    .Call(`_speaker_intensity_down_to_intensity_tier`, intensity_xptr)
}

.intensitytier_create <- function(tmin, tmax) {
    .Call(`_speaker_intensitytier_create`, tmin, tmax)
}

.intensitytier_get_start_time <- function(tier) {
    .Call(`_speaker_intensitytier_get_start_time`, tier)
}

.intensitytier_get_end_time <- function(tier) {
    .Call(`_speaker_intensitytier_get_end_time`, tier)
}

.intensitytier_get_number_of_points <- function(tier) {
    .Call(`_speaker_intensitytier_get_number_of_points`, tier)
}

.intensitytier_get_time_from_index <- function(tier, index) {
    .Call(`_speaker_intensitytier_get_time_from_index`, tier, index)
}

.intensitytier_get_value_at_index <- function(tier, index) {
    .Call(`_speaker_intensitytier_get_value_at_index`, tier, index)
}

.intensitytier_get_value_at_time <- function(tier, time) {
    .Call(`_speaker_intensitytier_get_value_at_time`, tier, time)
}

.intensitytier_get_mean <- function(tier, tmin, tmax) {
    .Call(`_speaker_intensitytier_get_mean`, tier, tmin, tmax)
}

.intensitytier_add_point <- function(tier, time, value) {
    invisible(.Call(`_speaker_intensitytier_add_point`, tier, time, value))
}

.intensitytier_remove_point <- function(tier, index) {
    invisible(.Call(`_speaker_intensitytier_remove_point`, tier, index))
}

.intensitytier_save <- function(tier, path) {
    invisible(.Call(`_speaker_intensitytier_save`, tier, path))
}

.intensitytier_read <- function(path) {
    .Call(`_speaker_intensitytier_read`, path)
}

.ltas_get_bin_from_frequency <- function(xptr, frequency) {
    .Call(`_speaker_ltas_get_bin_from_frequency`, xptr, frequency)
}

.ltas_get_frequency_from_bin <- function(xptr, bin) {
    .Call(`_speaker_ltas_get_frequency_from_bin`, xptr, bin)
}

.ltas_get_number_of_bins <- function(xptr) {
    .Call(`_speaker_ltas_get_number_of_bins`, xptr)
}

.ltas_get_bin_width <- function(xptr) {
    .Call(`_speaker_ltas_get_bin_width`, xptr)
}

.ltas_get_lowest_frequency <- function(xptr) {
    .Call(`_speaker_ltas_get_lowest_frequency`, xptr)
}

.ltas_get_highest_frequency <- function(xptr) {
    .Call(`_speaker_ltas_get_highest_frequency`, xptr)
}

.ltas_get_value_at_frequency <- function(xptr, frequency, unit, interpolate) {
    .Call(`_speaker_ltas_get_value_at_frequency`, xptr, frequency, unit, interpolate)
}

.ltas_get_minimum <- function(xptr, fmin, fmax, unit, interpolate) {
    .Call(`_speaker_ltas_get_minimum`, xptr, fmin, fmax, unit, interpolate)
}

.ltas_get_maximum <- function(xptr, fmin, fmax, unit, interpolate) {
    .Call(`_speaker_ltas_get_maximum`, xptr, fmin, fmax, unit, interpolate)
}

.ltas_get_mean <- function(xptr, fmin, fmax, unit) {
    .Call(`_speaker_ltas_get_mean`, xptr, fmin, fmax, unit)
}

.ltas_get_slope <- function(xptr, f1min, f1max, f2min, f2max, unit) {
    .Call(`_speaker_ltas_get_slope`, xptr, f1min, f1max, f2min, f2max, unit)
}

.ltas_compute_trend_line <- function(xptr, fmin, fmax) {
    .Call(`_speaker_ltas_compute_trend_line`, xptr, fmin, fmax)
}

.ltas_subtract_trend_line <- function(xptr, fmin, fmax) {
    .Call(`_speaker_ltas_subtract_trend_line`, xptr, fmin, fmax)
}

.ltas_as_data_frame <- function(xptr) {
    .Call(`_speaker_ltas_as_data_frame`, xptr)
}

.ltas_as_matrix <- function(xptr) {
    .Call(`_speaker_ltas_as_matrix`, xptr)
}

.manipulation_from_sound <- function(sound, time_step, pitch_floor, pitch_ceiling) {
    .Call(`_speaker_manipulation_from_sound`, sound, time_step, pitch_floor, pitch_ceiling)
}

.manipulation_get_start_time <- function(manip) {
    .Call(`_speaker_manipulation_get_start_time`, manip)
}

.manipulation_get_end_time <- function(manip) {
    .Call(`_speaker_manipulation_get_end_time`, manip)
}

.manipulation_extract_pitch_tier <- function(manip) {
    .Call(`_speaker_manipulation_extract_pitch_tier`, manip)
}

.manipulation_extract_duration_tier <- function(manip) {
    .Call(`_speaker_manipulation_extract_duration_tier`, manip)
}

.manipulation_extract_pulses <- function(manip) {
    .Call(`_speaker_manipulation_extract_pulses`, manip)
}

.manipulation_extract_original_sound <- function(manip) {
    .Call(`_speaker_manipulation_extract_original_sound`, manip)
}

.manipulation_replace_pitch_tier <- function(manip, pitch_tier) {
    invisible(.Call(`_speaker_manipulation_replace_pitch_tier`, manip, pitch_tier))
}

.manipulation_replace_duration_tier <- function(manip, duration_tier) {
    invisible(.Call(`_speaker_manipulation_replace_duration_tier`, manip, duration_tier))
}

.manipulation_get_resynthesis_overlap_add <- function(manip) {
    .Call(`_speaker_manipulation_get_resynthesis_overlap_add`, manip)
}

.manipulation_get_resynthesis_lpc <- function(manip) {
    .Call(`_speaker_manipulation_get_resynthesis_lpc`, manip)
}

.pitch_from_sound <- function(sound, time_step, pitch_floor, pitch_ceiling) {
    .Call(`_speaker_pitch_from_sound`, sound, time_step, pitch_floor, pitch_ceiling)
}

.pitch_get_time_from_frame <- function(pitch, frame_number) {
    .Call(`_speaker_pitch_get_time_from_frame`, pitch, frame_number)
}

.pitch_get_frame_from_time <- function(pitch, time) {
    .Call(`_speaker_pitch_get_frame_from_time`, pitch, time)
}

.pitch_get_number_of_frames <- function(pitch) {
    .Call(`_speaker_pitch_get_number_of_frames`, pitch)
}

.pitch_get_time_step <- function(pitch) {
    .Call(`_speaker_pitch_get_time_step`, pitch)
}

.pitch_get_value_at_time <- function(pitch, time, unit, interpolate) {
    .Call(`_speaker_pitch_get_value_at_time`, pitch, time, unit, interpolate)
}

.pitch_get_mean <- function(pitch, from_time, to_time, unit) {
    .Call(`_speaker_pitch_get_mean`, pitch, from_time, to_time, unit)
}

.pitch_get_standard_deviation <- function(pitch, from_time, to_time, unit) {
    .Call(`_speaker_pitch_get_standard_deviation`, pitch, from_time, to_time, unit)
}

.pitch_get_quantile <- function(pitch, from_time, to_time, quantile, unit) {
    .Call(`_speaker_pitch_get_quantile`, pitch, from_time, to_time, quantile, unit)
}

.pitch_get_minimum <- function(pitch, from_time, to_time, unit, interpolate) {
    .Call(`_speaker_pitch_get_minimum`, pitch, from_time, to_time, unit, interpolate)
}

.pitch_get_maximum <- function(pitch, from_time, to_time, unit, interpolate) {
    .Call(`_speaker_pitch_get_maximum`, pitch, from_time, to_time, unit, interpolate)
}

.pitch_get_time_of_minimum <- function(pitch, from_time, to_time, unit, interpolate) {
    .Call(`_speaker_pitch_get_time_of_minimum`, pitch, from_time, to_time, unit, interpolate)
}

.pitch_get_time_of_maximum <- function(pitch, from_time, to_time, unit, interpolate) {
    .Call(`_speaker_pitch_get_time_of_maximum`, pitch, from_time, to_time, unit, interpolate)
}

.pitch_count_voiced_frames <- function(pitch) {
    .Call(`_speaker_pitch_count_voiced_frames`, pitch)
}

.pitch_as_matrix <- function(pitch) {
    .Call(`_speaker_pitch_as_matrix`, pitch)
}

.pitch_as_data_frame <- function(pitch) {
    .Call(`_speaker_pitch_as_data_frame`, pitch)
}

.pitch_save <- function(pitch, path) {
    invisible(.Call(`_speaker_pitch_save`, pitch, path))
}

.pitch_to_point_process <- function(pitch) {
    .Call(`_speaker_pitch_to_point_process`, pitch)
}

.pitch_down_to_pitch_tier <- function(pitch) {
    .Call(`_speaker_pitch_down_to_pitch_tier`, pitch)
}

.pitchtier_create <- function(tmin, tmax) {
    .Call(`_speaker_pitchtier_create`, tmin, tmax)
}

.pitchtier_get_start_time <- function(tier) {
    .Call(`_speaker_pitchtier_get_start_time`, tier)
}

.pitchtier_get_end_time <- function(tier) {
    .Call(`_speaker_pitchtier_get_end_time`, tier)
}

.pitchtier_get_number_of_points <- function(tier) {
    .Call(`_speaker_pitchtier_get_number_of_points`, tier)
}

.pitchtier_get_time_from_index <- function(tier, index) {
    .Call(`_speaker_pitchtier_get_time_from_index`, tier, index)
}

.pitchtier_get_value_at_index <- function(tier, index) {
    .Call(`_speaker_pitchtier_get_value_at_index`, tier, index)
}

.pitchtier_get_value_at_time <- function(tier, time) {
    .Call(`_speaker_pitchtier_get_value_at_time`, tier, time)
}

.pitchtier_get_mean <- function(tier, tmin, tmax) {
    .Call(`_speaker_pitchtier_get_mean`, tier, tmin, tmax)
}

.pitchtier_add_point <- function(tier, time, value) {
    invisible(.Call(`_speaker_pitchtier_add_point`, tier, time, value))
}

.pitchtier_remove_point <- function(tier, index) {
    invisible(.Call(`_speaker_pitchtier_remove_point`, tier, index))
}

.pitchtier_remove_points_between <- function(tier, tmin, tmax) {
    invisible(.Call(`_speaker_pitchtier_remove_points_between`, tier, tmin, tmax))
}

.pitchtier_multiply_frequencies <- function(tier, factor) {
    invisible(.Call(`_speaker_pitchtier_multiply_frequencies`, tier, factor))
}

.pitchtier_shift_frequencies <- function(tier, shift) {
    invisible(.Call(`_speaker_pitchtier_shift_frequencies`, tier, shift))
}

.pitchtier_stylize <- function(tier, frequency_resolution, use_semitones) {
    invisible(.Call(`_speaker_pitchtier_stylize`, tier, frequency_resolution, use_semitones))
}

.pitchtier_save <- function(tier, path) {
    invisible(.Call(`_speaker_pitchtier_save`, tier, path))
}

.pitchtier_read <- function(path) {
    .Call(`_speaker_pitchtier_read`, path)
}

.pointprocess_get_number_of_points <- function(xptr) {
    .Call(`_speaker_pointprocess_get_number_of_points`, xptr)
}

.pointprocess_get_time_from_index <- function(xptr, index) {
    .Call(`_speaker_pointprocess_get_time_from_index`, xptr, index)
}

.pointprocess_get_nearest_index <- function(xptr, time) {
    .Call(`_speaker_pointprocess_get_nearest_index`, xptr, time)
}

.pointprocess_get_low_index <- function(xptr, time) {
    .Call(`_speaker_pointprocess_get_low_index`, xptr, time)
}

.pointprocess_get_high_index <- function(xptr, time) {
    .Call(`_speaker_pointprocess_get_high_index`, xptr, time)
}

.pointprocess_get_interval <- function(xptr, time) {
    .Call(`_speaker_pointprocess_get_interval`, xptr, time)
}

.pointprocess_get_jitter_local <- function(xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor) {
    .Call(`_speaker_pointprocess_get_jitter_local`, xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor)
}

.pointprocess_get_jitter_local_absolute <- function(xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor) {
    .Call(`_speaker_pointprocess_get_jitter_local_absolute`, xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor)
}

.pointprocess_get_jitter_rap <- function(xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor) {
    .Call(`_speaker_pointprocess_get_jitter_rap`, xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor)
}

.pointprocess_get_jitter_ppq5 <- function(xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor) {
    .Call(`_speaker_pointprocess_get_jitter_ppq5`, xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor)
}

.pointprocess_get_jitter_ddp <- function(xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor) {
    .Call(`_speaker_pointprocess_get_jitter_ddp`, xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor)
}

.pointprocess_sound_get_shimmer_local <- function(pp_xptr, sound_xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor, max_amplitude_factor) {
    .Call(`_speaker_pointprocess_sound_get_shimmer_local`, pp_xptr, sound_xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor, max_amplitude_factor)
}

.pointprocess_sound_get_shimmer_local_db <- function(pp_xptr, sound_xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor, max_amplitude_factor) {
    .Call(`_speaker_pointprocess_sound_get_shimmer_local_db`, pp_xptr, sound_xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor, max_amplitude_factor)
}

.pointprocess_sound_get_shimmer_apq3 <- function(pp_xptr, sound_xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor, max_amplitude_factor) {
    .Call(`_speaker_pointprocess_sound_get_shimmer_apq3`, pp_xptr, sound_xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor, max_amplitude_factor)
}

.pointprocess_sound_get_shimmer_apq5 <- function(pp_xptr, sound_xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor, max_amplitude_factor) {
    .Call(`_speaker_pointprocess_sound_get_shimmer_apq5`, pp_xptr, sound_xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor, max_amplitude_factor)
}

.pointprocess_sound_get_shimmer_apq11 <- function(pp_xptr, sound_xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor, max_amplitude_factor) {
    .Call(`_speaker_pointprocess_sound_get_shimmer_apq11`, pp_xptr, sound_xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor, max_amplitude_factor)
}

.pointprocess_sound_get_shimmer_dda <- function(pp_xptr, sound_xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor, max_amplitude_factor) {
    .Call(`_speaker_pointprocess_sound_get_shimmer_dda`, pp_xptr, sound_xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor, max_amplitude_factor)
}

.pointprocess_get_mean_period <- function(xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor) {
    .Call(`_speaker_pointprocess_get_mean_period`, xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor)
}

.pointprocess_get_stdev_period <- function(xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor) {
    .Call(`_speaker_pointprocess_get_stdev_period`, xptr, from_time, to_time, period_floor, period_ceiling, max_period_factor)
}

.pointprocess_add_point <- function(xptr, time) {
    invisible(.Call(`_speaker_pointprocess_add_point`, xptr, time))
}

.pointprocess_remove_point <- function(xptr, index) {
    invisible(.Call(`_speaker_pointprocess_remove_point`, xptr, index))
}

.pointprocess_remove_point_near <- function(xptr, time) {
    invisible(.Call(`_speaker_pointprocess_remove_point_near`, xptr, time))
}

.pointprocess_remove_points_between <- function(xptr, from_time, to_time) {
    invisible(.Call(`_speaker_pointprocess_remove_points_between`, xptr, from_time, to_time))
}

.pointprocess_save <- function(xptr, path) {
    invisible(.Call(`_speaker_pointprocess_save`, xptr, path))
}

#' Get Praat version information
#'
#' Returns the version string for the Praat library integration
#'
#' @return Character string with version information
#' @export
praat_version <- function() {
    .Call(`_speaker_praat_version`)
}

#' Initialize Praat library
#'
#' Performs any necessary initialization for Praat components
#' This should be called when the package is loaded
#'
#' @return Logical indicating success
#' @keywords internal
praat_initialize <- function() {
    .Call(`_speaker_praat_initialize`)
}

#' Calculate basic sound statistics
#'
#' Calculates basic statistics for a sound vector
#'
#' @param sound_data Numeric vector containing sound amplitude values
#' @return List containing mean, min, max, and length statistics
#' @keywords internal
sound_stats <- function(sound_data) {
    .Call(`_speaker_sound_stats`, sound_data)
}

#' Create a sound object from numeric vector
#'
#' Creates a praat_sound object structure from R numeric data
#'
#' @param values Numeric vector of sound amplitude values
#' @param sampling_rate Sampling rate in Hz (default: 44100)
#' @param start_time Start time in seconds (default: 0.0)
#' @return List representing a praat_sound object with values and metadata
#' @export
create_sound_from_values <- function(values, sampling_rate = 44100.0, start_time = 0.0) {
    .Call(`_speaker_create_sound_from_values`, values, sampling_rate, start_time)
}

#' Get sound duration
#'
#' Extract the duration of a sound object in seconds
#'
#' @param sound_obj List representing a praat_sound object
#' @return Numeric value representing duration in seconds
#' @keywords internal
get_sound_duration_cpp <- function(sound_obj) {
    .Call(`_speaker_get_sound_duration_cpp`, sound_obj)
}

#' Get sound sampling rate
#'
#' Extract the sampling rate of a sound object
#'
#' @param sound_obj List representing a praat_sound object
#' @return Numeric value representing sampling rate in Hz
#' @keywords internal
get_sound_sampling_rate_cpp <- function(sound_obj) {
    .Call(`_speaker_get_sound_sampling_rate_cpp`, sound_obj)
}

#' Get number of samples in sound
#'
#' Extract the number of samples in a sound object
#'
#' @param sound_obj List representing a praat_sound object
#' @return Integer number of samples
#' @keywords internal
get_sound_n_samples_cpp <- function(sound_obj) {
    .Call(`_speaker_get_sound_n_samples_cpp`, sound_obj)
}

#' Read Sound from file (internal)
#' @keywords internal
.sound_read_from_file <- function(path) {
    .Call(`_speaker_sound_read_from_file`, path)
}

#' Create Sound from values (internal)
#' @keywords internal
.sound_create_from_values <- function(values, sampling_rate) {
    .Call(`_speaker_sound_create_from_values`, values, sampling_rate)
}

#' Create simple tone (internal)
#' @keywords internal
.sound_create_tone <- function(duration, sampling_rate, frequency, amplitude) {
    .Call(`_speaker_sound_create_tone`, duration, sampling_rate, frequency, amplitude)
}

#' Get sound duration (internal)
#' @keywords internal
.sound_get_duration <- function(xptr) {
    .Call(`_speaker_sound_get_duration`, xptr)
}

#' Get sampling frequency (internal)
#' @keywords internal
.sound_get_sampling_frequency <- function(xptr) {
    .Call(`_speaker_sound_get_sampling_frequency`, xptr)
}

#' Get number of samples (internal)
#' @keywords internal
.sound_get_number_of_samples <- function(xptr) {
    .Call(`_speaker_sound_get_number_of_samples`, xptr)
}

#' Get number of channels (internal)
#' @keywords internal
.sound_get_number_of_channels <- function(xptr) {
    .Call(`_speaker_sound_get_number_of_channels`, xptr)
}

#' Get value at time (internal)
#' @keywords internal
.sound_get_value_at_time <- function(xptr, time, channel) {
    .Call(`_speaker_sound_get_value_at_time`, xptr, time, channel)
}

#' Get RMS (internal)
#' @keywords internal
.sound_get_rms <- function(xptr, from_time, to_time) {
    .Call(`_speaker_sound_get_rms`, xptr, from_time, to_time)
}

#' Get energy (internal)
#' @keywords internal
.sound_get_energy <- function(xptr, from_time, to_time) {
    .Call(`_speaker_sound_get_energy`, xptr, from_time, to_time)
}

#' Get power (internal)
#' @keywords internal
.sound_get_power <- function(xptr, from_time, to_time) {
    .Call(`_speaker_sound_get_power`, xptr, from_time, to_time)
}

#' Get intensity in dB (internal)
#' @keywords internal
.sound_get_intensity_db <- function(xptr) {
    .Call(`_speaker_sound_get_intensity_db`, xptr)
}

#' Convert Sound to Pitch (internal)
#' @keywords internal
.sound_to_pitch <- function(sound_xptr, time_step, pitch_floor, pitch_ceiling) {
    .Call(`_speaker_sound_to_pitch`, sound_xptr, time_step, pitch_floor, pitch_ceiling)
}

#' Convert Sound to Formant via Burg (internal)
#' @keywords internal
.sound_to_formant_burg <- function(sound_xptr, time_step, max_formants, max_frequency, window_length, pre_emphasis_from) {
    .Call(`_speaker_sound_to_formant_burg`, sound_xptr, time_step, max_formants, max_frequency, window_length, pre_emphasis_from)
}

#' Convert Sound to Intensity (internal)
#' @keywords internal
.sound_to_intensity <- function(sound_xptr, minimum_pitch, time_step, subtract_mean) {
    .Call(`_speaker_sound_to_intensity`, sound_xptr, minimum_pitch, time_step, subtract_mean)
}

#' Convert Sound to Harmonicity (internal)
#' @keywords internal
.sound_to_harmonicity_cc <- function(sound_xptr, time_step, min_pitch, silence_threshold, periods_per_window) {
    .Call(`_speaker_sound_to_harmonicity_cc`, sound_xptr, time_step, min_pitch, silence_threshold, periods_per_window)
}

#' Convert Sound to Spectrum (internal)
#' @keywords internal
.sound_to_spectrum <- function(sound_xptr, fast) {
    .Call(`_speaker_sound_to_spectrum`, sound_xptr, fast)
}

#' Convert Sound to Ltas (internal)
#' @keywords internal
.sound_to_ltas <- function(sound_xptr, bandwidth) {
    .Call(`_speaker_sound_to_ltas`, sound_xptr, bandwidth)
}

#' Convert Sound to Spectrogram (internal)
#' @keywords internal
.sound_to_spectrogram <- function(sound_xptr, window_length, max_frequency, time_step, frequency_step, window_shape) {
    .Call(`_speaker_sound_to_spectrogram`, sound_xptr, window_length, max_frequency, time_step, frequency_step, window_shape)
}

#' Export Sound as data frame (internal)
#' @keywords internal
.sound_as_data_frame <- function(xptr) {
    .Call(`_speaker_sound_as_data_frame`, xptr)
}

#' Export Sound as matrix (internal)
#' @keywords internal
.sound_as_matrix <- function(xptr) {
    .Call(`_speaker_sound_as_matrix`, xptr)
}

#' Save Sound to file (internal)
#' @keywords internal
.sound_save <- function(xptr, path, file_type) {
    invisible(.Call(`_speaker_sound_save`, xptr, path, file_type))
}

#' Extract glottal pulses from sound using cross-correlation (internal)
#' @keywords internal
.sound_to_point_process_periodic_cc <- function(xptr, time_step, pitch_floor, pitch_ceiling, max_period_factor, max_amplitude_factor) {
    .Call(`_speaker_sound_to_point_process_periodic_cc`, xptr, time_step, pitch_floor, pitch_ceiling, max_period_factor, max_amplitude_factor)
}

#' Extract extrema (peaks) from sound (internal)
#' @keywords internal
.sound_to_point_process_extrema <- function(xptr, channel, include_maxima, include_minima, interpolation) {
    .Call(`_speaker_sound_to_point_process_extrema`, xptr, channel, include_maxima, include_minima, interpolation)
}

#' Extract zero crossings from sound (internal)
#' @keywords internal
.sound_to_point_process_zeros <- function(xptr, channel, include_raisers, include_fallers) {
    .Call(`_speaker_sound_to_point_process_zeros`, xptr, channel, include_raisers, include_fallers)
}

#' Extract a specific channel from Sound (internal)
#' @keywords internal
.sound_extract_channel <- function(xptr, channel) {
    .Call(`_speaker_sound_extract_channel`, xptr, channel)
}

#' Extract part of Sound by time (internal)
#' @keywords internal
.sound_extract_part <- function(xptr, from_time, to_time, window_shape, relative_width, preserve_times) {
    .Call(`_speaker_sound_extract_part`, xptr, from_time, to_time, window_shape, relative_width, preserve_times)
}

#' Scale intensity of Sound to target dB level (internal)
#' @keywords internal
.sound_scale_intensity <- function(xptr, new_intensity_db) {
    invisible(.Call(`_speaker_sound_scale_intensity`, xptr, new_intensity_db))
}

#' Scale peak amplitude of Sound (internal)
#' @keywords internal
.sound_scale_peak <- function(xptr, new_peak) {
    invisible(.Call(`_speaker_sound_scale_peak`, xptr, new_peak))
}

#' Pre-emphasize Sound (high-pass filter) (internal)
#' @keywords internal
.sound_pre_emphasize <- function(xptr, from_frequency) {
    invisible(.Call(`_speaker_sound_pre_emphasize`, xptr, from_frequency))
}

#' De-emphasize Sound (low-pass filter) (internal)
#' @keywords internal
.sound_de_emphasize <- function(xptr, from_frequency) {
    invisible(.Call(`_speaker_sound_de_emphasize`, xptr, from_frequency))
}

#' Resample Sound to new sampling frequency (internal)
#' @keywords internal
.sound_resample <- function(xptr, new_frequency, precision) {
    .Call(`_speaker_sound_resample`, xptr, new_frequency, precision)
}

#' Convert Sound to mono by averaging channels (internal)
#' @keywords internal
.sound_convert_to_mono <- function(xptr) {
    .Call(`_speaker_sound_convert_to_mono`, xptr)
}

#' Convert mono Sound to stereo by duplicating channel (internal)
#' @keywords internal
.sound_convert_to_stereo <- function(xptr) {
    .Call(`_speaker_sound_convert_to_stereo`, xptr)
}

#' Copy Sound object (internal)
#' @keywords internal
.sound_copy <- function(xptr) {
    .Call(`_speaker_sound_copy`, xptr)
}

#' Concatenate two Sound objects (internal)
#' @keywords internal
.sound_concatenate <- function(xptr1, xptr2, overlap) {
    .Call(`_speaker_sound_concatenate`, xptr1, xptr2, overlap)
}

#' Mix two Sound objects (internal)
#' @keywords internal
.sound_mix <- function(xptr1, xptr2, balance) {
    .Call(`_speaker_sound_mix`, xptr1, xptr2, balance)
}

.spectrogram_get_start_time <- function(spectrogram) {
    .Call(`_speaker_spectrogram_get_start_time`, spectrogram)
}

.spectrogram_get_end_time <- function(spectrogram) {
    .Call(`_speaker_spectrogram_get_end_time`, spectrogram)
}

.spectrogram_get_time_step <- function(spectrogram) {
    .Call(`_speaker_spectrogram_get_time_step`, spectrogram)
}

.spectrogram_get_number_of_time_bins <- function(spectrogram) {
    .Call(`_speaker_spectrogram_get_number_of_time_bins`, spectrogram)
}

.spectrogram_get_lowest_frequency <- function(spectrogram) {
    .Call(`_speaker_spectrogram_get_lowest_frequency`, spectrogram)
}

.spectrogram_get_highest_frequency <- function(spectrogram) {
    .Call(`_speaker_spectrogram_get_highest_frequency`, spectrogram)
}

.spectrogram_get_frequency_step <- function(spectrogram) {
    .Call(`_speaker_spectrogram_get_frequency_step`, spectrogram)
}

.spectrogram_get_number_of_frequency_bins <- function(spectrogram) {
    .Call(`_speaker_spectrogram_get_number_of_frequency_bins`, spectrogram)
}

.spectrogram_get_time_from_frame <- function(spectrogram, frame) {
    .Call(`_speaker_spectrogram_get_time_from_frame`, spectrogram, frame)
}

.spectrogram_get_frequency_from_bin <- function(spectrogram, bin) {
    .Call(`_speaker_spectrogram_get_frequency_from_bin`, spectrogram, bin)
}

.spectrogram_get_power_at <- function(spectrogram, time, frequency) {
    .Call(`_speaker_spectrogram_get_power_at`, spectrogram, time, frequency)
}

.spectrogram_to_spectrum <- function(spectrogram, time) {
    .Call(`_speaker_spectrogram_to_spectrum`, spectrogram, time)
}

.spectrogram_as_matrix <- function(spectrogram) {
    .Call(`_speaker_spectrogram_as_matrix`, spectrogram)
}

.spectrum_get_lowest_frequency <- function(xptr) {
    .Call(`_speaker_spectrum_get_lowest_frequency`, xptr)
}

.spectrum_get_highest_frequency <- function(xptr) {
    .Call(`_speaker_spectrum_get_highest_frequency`, xptr)
}

.spectrum_get_number_of_bins <- function(xptr) {
    .Call(`_speaker_spectrum_get_number_of_bins`, xptr)
}

.spectrum_get_frequency_step <- function(xptr) {
    .Call(`_speaker_spectrum_get_frequency_step`, xptr)
}

.spectrum_get_frequency_from_bin <- function(xptr, bin) {
    .Call(`_speaker_spectrum_get_frequency_from_bin`, xptr, bin)
}

.spectrum_get_bin_from_frequency <- function(xptr, frequency) {
    .Call(`_speaker_spectrum_get_bin_from_frequency`, xptr, frequency)
}

.spectrum_get_real_value_in_bin <- function(xptr, bin) {
    .Call(`_speaker_spectrum_get_real_value_in_bin`, xptr, bin)
}

.spectrum_get_imaginary_value_in_bin <- function(xptr, bin) {
    .Call(`_speaker_spectrum_get_imaginary_value_in_bin`, xptr, bin)
}

.spectrum_get_band_density <- function(xptr, fmin, fmax) {
    .Call(`_speaker_spectrum_get_band_density`, xptr, fmin, fmax)
}

.spectrum_get_band_energy <- function(xptr, fmin, fmax) {
    .Call(`_speaker_spectrum_get_band_energy`, xptr, fmin, fmax)
}

.spectrum_get_centre_of_gravity <- function(xptr, power) {
    .Call(`_speaker_spectrum_get_centre_of_gravity`, xptr, power)
}

.spectrum_get_standard_deviation <- function(xptr, power) {
    .Call(`_speaker_spectrum_get_standard_deviation`, xptr, power)
}

.spectrum_get_skewness <- function(xptr, power) {
    .Call(`_speaker_spectrum_get_skewness`, xptr, power)
}

.spectrum_get_kurtosis <- function(xptr, power) {
    .Call(`_speaker_spectrum_get_kurtosis`, xptr, power)
}

.spectrum_get_central_moment <- function(xptr, moment, power) {
    .Call(`_speaker_spectrum_get_central_moment`, xptr, moment, power)
}

.spectrum_pass_hann_band <- function(xptr, fmin, fmax, smooth) {
    invisible(.Call(`_speaker_spectrum_pass_hann_band`, xptr, fmin, fmax, smooth))
}

.spectrum_stop_hann_band <- function(xptr, fmin, fmax, smooth) {
    invisible(.Call(`_speaker_spectrum_stop_hann_band`, xptr, fmin, fmax, smooth))
}

.spectrum_cepstral_smoothing <- function(spectrum, bandwidth) {
    .Call(`_speaker_spectrum_cepstral_smoothing`, spectrum, bandwidth)
}

.spectrum_to_sound <- function(spectrum) {
    .Call(`_speaker_spectrum_to_sound`, spectrum)
}

.spectrum_as_matrix <- function(xptr) {
    .Call(`_speaker_spectrum_as_matrix`, xptr)
}

.textgrid_read_from_file <- function(path) {
    .Call(`_speaker_textgrid_read_from_file`, path)
}

.textgrid_create <- function(tmin, tmax, tier_names = "", point_tiers = "") {
    .Call(`_speaker_textgrid_create`, tmin, tmax, tier_names, point_tiers)
}

.textgrid_save <- function(xptr, path) {
    invisible(.Call(`_speaker_textgrid_save`, xptr, path))
}

.textgrid_get_start_time <- function(xptr) {
    .Call(`_speaker_textgrid_get_start_time`, xptr)
}

.textgrid_get_end_time <- function(xptr) {
    .Call(`_speaker_textgrid_get_end_time`, xptr)
}

.textgrid_get_total_duration <- function(xptr) {
    .Call(`_speaker_textgrid_get_total_duration`, xptr)
}

.textgrid_get_number_of_tiers <- function(xptr) {
    .Call(`_speaker_textgrid_get_number_of_tiers`, xptr)
}

.textgrid_get_tier_name <- function(xptr, tier_number) {
    .Call(`_speaker_textgrid_get_tier_name`, xptr, tier_number)
}

.textgrid_get_tier_names <- function(xptr) {
    .Call(`_speaker_textgrid_get_tier_names`, xptr)
}

.textgrid_tier_is_interval_tier <- function(xptr, tier_number) {
    .Call(`_speaker_textgrid_tier_is_interval_tier`, xptr, tier_number)
}

.textgrid_tier_is_point_tier <- function(xptr, tier_number) {
    .Call(`_speaker_textgrid_tier_is_point_tier`, xptr, tier_number)
}

.textgrid_get_number_of_intervals <- function(xptr, tier_number) {
    .Call(`_speaker_textgrid_get_number_of_intervals`, xptr, tier_number)
}

.textgrid_get_interval_start_time <- function(xptr, tier_number, interval_number) {
    .Call(`_speaker_textgrid_get_interval_start_time`, xptr, tier_number, interval_number)
}

.textgrid_get_interval_end_time <- function(xptr, tier_number, interval_number) {
    .Call(`_speaker_textgrid_get_interval_end_time`, xptr, tier_number, interval_number)
}

.textgrid_get_interval_text <- function(xptr, tier_number, interval_number) {
    .Call(`_speaker_textgrid_get_interval_text`, xptr, tier_number, interval_number)
}

.textgrid_get_interval_at_time <- function(xptr, tier_number, time) {
    .Call(`_speaker_textgrid_get_interval_at_time`, xptr, tier_number, time)
}

.textgrid_get_label_at_time <- function(xptr, tier_number, time) {
    .Call(`_speaker_textgrid_get_label_at_time`, xptr, tier_number, time)
}

.textgrid_set_interval_text <- function(xptr, tier_number, interval_number, text) {
    invisible(.Call(`_speaker_textgrid_set_interval_text`, xptr, tier_number, interval_number, text))
}

.textgrid_insert_boundary <- function(xptr, tier_number, time) {
    invisible(.Call(`_speaker_textgrid_insert_boundary`, xptr, tier_number, time))
}

.textgrid_remove_boundary <- function(xptr, tier_number, time) {
    invisible(.Call(`_speaker_textgrid_remove_boundary`, xptr, tier_number, time))
}

.textgrid_get_number_of_points <- function(xptr, tier_number) {
    .Call(`_speaker_textgrid_get_number_of_points`, xptr, tier_number)
}

.textgrid_get_point_time <- function(xptr, tier_number, point_number) {
    .Call(`_speaker_textgrid_get_point_time`, xptr, tier_number, point_number)
}

.textgrid_get_point_text <- function(xptr, tier_number, point_number) {
    .Call(`_speaker_textgrid_get_point_text`, xptr, tier_number, point_number)
}

.textgrid_insert_point <- function(xptr, tier_number, time, mark) {
    invisible(.Call(`_speaker_textgrid_insert_point`, xptr, tier_number, time, mark))
}

.textgrid_set_point_text <- function(xptr, tier_number, point_number, text) {
    invisible(.Call(`_speaker_textgrid_set_point_text`, xptr, tier_number, point_number, text))
}

.textgrid_remove_point <- function(xptr, tier_number, point_number) {
    invisible(.Call(`_speaker_textgrid_remove_point`, xptr, tier_number, point_number))
}

.textgrid_add_interval_tier <- function(xptr, name) {
    invisible(.Call(`_speaker_textgrid_add_interval_tier`, xptr, name))
}

.textgrid_add_point_tier <- function(xptr, name) {
    invisible(.Call(`_speaker_textgrid_add_point_tier`, xptr, name))
}

.textgrid_remove_tier <- function(xptr, tier_number) {
    invisible(.Call(`_speaker_textgrid_remove_tier`, xptr, tier_number))
}

.textgrid_extract_part <- function(xptr, start_time, end_time, preserve_times) {
    .Call(`_speaker_textgrid_extract_part`, xptr, start_time, end_time, preserve_times)
}

.textgrid_to_data_frame <- function(xptr, tier_numbers = NULL) {
    .Call(`_speaker_textgrid_to_data_frame`, xptr, tier_numbers)
}

#' Safe error wrapper for Praat calls
#'
#' Provides a consistent error handling pattern for Praat operations
#'
#' @param context Description of what operation failed
#' @keywords internal
NULL

#' Validate positive numeric parameter
#'
#' Ensures a numeric parameter is positive (> 0)
#'
#' @param value The value to check
#' @param param_name Name of the parameter for error messages
#' @keywords internal
NULL

#' Validate non-negative numeric parameter
#'
#' Ensures a numeric parameter is non-negative (>= 0)
#'
#' @param value The value to check
#' @param param_name Name of the parameter for error messages
#' @keywords internal
NULL

#' Validate numeric parameter is in range
#'
#' Ensures a numeric parameter falls within a specified range
#'
#' @param value The value to check
#' @param min_val Minimum allowed value (inclusive)
#' @param max_val Maximum allowed value (inclusive)
#' @param param_name Name of the parameter for error messages
#' @keywords internal
NULL

#' Validate integer parameter is positive
#'
#' Ensures an integer parameter is positive (> 0)
#'
#' @param value The value to check
#' @param param_name Name of the parameter for error messages
#' @keywords internal
NULL

#' Validate that an R list represents a valid sound object
#'
#' Checks that a list contains the required fields for a praat_sound object
#'
#' @param sound_obj R list representing a sound object
#' @return true if valid, throws error if invalid
#' @keywords internal
NULL

#' Validate that an R list represents a valid pitch object
#'
#' Checks that a list contains the required fields for a praat_pitch object
#'
#' @param pitch_obj R list representing a pitch object
#' @return true if valid, throws error if invalid
#' @keywords internal
NULL

#' Convert R logical to C++ bool with NA handling
#'
#' Safely converts R logical values to C++ bool, handling NA as false
#'
#' @param x R logical value
#' @param default_val Default value if NA
#' @return bool value
#' @keywords internal
NULL

#' Convert R numeric to C++ double with NA handling
#'
#' Safely converts R numeric values to C++ double
#'
#' @param x R numeric value
#' @return double value (returns R_NaN if NA)
#' @keywords internal
NULL

#' Convert Praat errors to R exceptions
#'
#' Wraps Praat function calls and converts Praat's error system to R exceptions
#'
#' @param error_msg Error message from Praat
#' @keywords internal
praat_error_to_r <- function(error_msg) {
    invisible(.Call(`_speaker_praat_error_to_r`, error_msg))
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_speaker_RcppExport_registerCCallable`)
})
